{
  "formatVersion": "1.1",
  "component": {
    "group": "com.atg.sdk",
    "module": "onefin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.1.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.1.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "8.1.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "8.1.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "8.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "onefin-1.0.0.aar",
          "url": "onefin-1.0.0.aar",
          "size": 2078870,
          "sha512": "2eacd7b182841ab49c5b9e67a4a80c6a3b6c1284f4b9583a4aa0d82499129d9863aa48d94f02b96fc5f42b95363f2e19a126f0a34932ca64927bf721d63e997a",
          "sha256": "575a1600aa081531dbfebe071bc159bc231aa0f4fe10eb4cb23799f6662e3413",
          "sha1": "c1f8e7fc530b618208334d48153edad2f0118fd8",
          "md5": "f9d4c07123f987a504ed97eafa235d33"
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.atg.pay",
          "module": "paylib",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.atg.core",
          "module": "payment",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "co.paystack.android.design.widget",
          "module": "pinpad",
          "version": {
            "requires": "1.0.8"
          }
        },
        {
          "group": "com.sunmi",
          "module": "printerlibrary",
          "version": {
            "requires": "1.0.14"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview-selection",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "6.6.6"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.70"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.1.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.1.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "8.1.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "8.1.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "8.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "onefin-1.0.0.aar",
          "url": "onefin-1.0.0.aar",
          "size": 2078870,
          "sha512": "2eacd7b182841ab49c5b9e67a4a80c6a3b6c1284f4b9583a4aa0d82499129d9863aa48d94f02b96fc5f42b95363f2e19a126f0a34932ca64927bf721d63e997a",
          "sha256": "575a1600aa081531dbfebe071bc159bc231aa0f4fe10eb4cb23799f6662e3413",
          "sha1": "c1f8e7fc530b618208334d48153edad2f0118fd8",
          "md5": "f9d4c07123f987a504ed97eafa235d33"
        }
      ]
    }
  ]
}
